# Generated by Django 4.2.9 on 2026-02-20 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conversations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='audio_response',
            field=models.FileField(blank=True, null=True, upload_to='audio/responses/'),
        ),
    ]
