# Generated by Django 4.2.9 on 2026-02-21 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avatars', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='avatar',
            name='language',
            field=models.CharField(choices=[('en', 'English'), ('hi', 'Hindi'), ('ta', 'Tamil'), ('te', 'Telugu'), ('mr', 'Marathi'), ('bn', 'Bengali'), ('gu', 'Gujarati'), ('kn', 'Kannada'), ('ml', 'Malayalam'), ('pa', 'Punjabi')], default='en', max_length=10),
        ),
    ]
